config/routes.rb
Rails.application.routes.draw do
  devise_for :web_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'games#index'

  get '/games', to: 'games#index'

  get '/event-by-code', to: 'events#show_by_code', as: 'event_by_code'

  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  before_create :set_event_code

  belongs_to :owner, foreign_key: 'user_id', class_name: 'User'

  has_and_belongs_to_many :users

  validates :location, presence: true
  validates :title, presence: true

  private

  def set_event_code
    self.code = SecureRandom.hex(10)[0..8]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events

  has_and_belongs_to_many :events_joined, class_name: 'Events'

  validates :nick, presence: true
end

app/models/web_user.rb
class WebUser < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_web_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = current_web_user.events.find(params[:id])
  end

  def show_by_code
    validator = EventCodeValidator.new(code: params[:code])

    if validator.valid?
      @event = Event.find_by(code: params[:code])
    else
      redirect_to root_path
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_web_user.events.build(event_params)

    if @event.save
      redirect_to games_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:location, :title, :description)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController # rubocop:disable Style/Documentation
  def index
    # @nickname = current_web_user.nick
    @events = current_web_user.events.order(created_at: :desc).limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nickname
    current_web_user.nick if web_user_signed_in?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/nick_helper.rb
module NickHelper
end

app/views/events/_event.html.erb
  <div class="container">
    
    <div class="event">
      <h1 class="hero hero--inline">
        <%=@event.title%>
      </h1>
    </div>
    
  </div>

app/views/events/_form.html.erb
<%= form_with class: 'events__form', model: event do |form| %>

  <div class="events__form__field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div class="events__form__field__errors"><%= message %></div>
    <% end %>
  </div>

  <div class="events__form__field">
    <%= form.label :location %>
    <%= form.text_field :location %>
    <% @event.errors.full_messages_for(:location).each do |message| %>
      <div class="events__form__field__errors"><%= message %></div>
    <% end %>
  </div>

  <div class="events__form__field">
    <%= form.label :description %>
    <%= form.text_area :description %>
    <% @event.errors.full_messages_for(:description).each do |message| %>
      <div class="events__form__field__errors"><%= message %></div>
    <% end %>
  </div>

  <div class="events__form__actions">
    <%= form.submit class: "btn btn--secondary" %>
    <%= link_to "Cancel", games_path, class: "btn btn--cancel" %>
  </div>

<% end %>

app/views/events/new.html.erb
<div class="container new__event__page">
  <h1 class="hero hero--inline">Create new event</h1>
  <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="event">
    <h1 class="hero hero--inline">
      (<%= @event.location %>) <%= @event.title %> - <%= @event.code %>
    </h1>
    <p class="event__description">
      <%= @event.description %>
    </p>
    <div class="event__participants">
      <h1>Participants</h1>
      <div class="event__participant event__participant--owner">
        <h1><%= @event.owner.nick %></h1>
        <h2>Owner of the event</h2>
      </div>
      <div class="event__participant">
        <h1>Bunyos Pityu</h1>
      </div>
      <div class="event__participant">
        <h1>Makiverem</h1>
      </div>
    </div>
  </div>
</div>

app/views/events/show_by_code.html.erb
<h1>Show by code</h1>
<% nickname %>
<h1><%= @event.title %></h1>

app/views/games/index.html.erb
<div class="container">
  <header class="welcome">
    <h1 class="welcome__message">Weclome <%= nickname %></h1>
  </header>

  <main class="dashboard">
    <section class="dashboard__controls">

      <%= link_to "Create Event", new_event_path,
                  class: "btn btn--primary dashboard__controls__create-btn", data: { "turbo-frame": "_top" } %>

      <div class="dashboard__events">
        <%= form_with url: event_by_code_path, method: :get do |form| %>
          <%= form.label :code, "Event Code" %>
          <%= form.text_field :code %>
          <%= form.submit "Find Event By Code" %>
        <% end %>
        <h2>My events</h2>
        <div class="dashboard__events__list">
          <% @events.each do |event| %>
            <article class="card">
              <h1 class="card__header">
                <%= link_to event.title, event, data: { "turbo-frame": "_top" } %>
              </h1>
              <div class="card__body">
                <ul>
                  <li>Location: <%= event.location %> </li>
                </ul>
              </div>
            </article>
          <% end %>
        </div>
      </div>
    </section>
    <section class="dashboard__upcoming">
      <div class="dashboard__upcoming__header">
        <h1>Upcoming events</h1>
      </div>
      <div class="dashboard__upcoming__item">
        <h2>Placeholder 1</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla aperiam ducimus maiores explicabo, ab officia
          at! Modi et porro illum, eligendi, vitae minima iure omnis ex culpa placeat officiis est odit sint. Blanditiis
          itaque minus nihil? Ut, ab maxime deleniti tempora optio, nesciunt hic velit voluptatem nulla sapiente ad
          quia.</p>
      </div>
      <div class="dashboard__upcoming__item">
        <h2>Placeholder 2</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla aperiam ducimus maiores explicabo, ab officia
          at! Modi et porro illum, eligendi, vitae minima iure omnis ex culpa placeat officiis est odit sint. Blanditiis
          itaque minus nihil? Ut, ab maxime deleniti tempora optio, nesciunt hic velit voluptatem nulla sapiente ad
          quia.</p>
      </div>
      <div class="dashboard__upcoming__item">
        <h2>Placeholder 3</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla aperiam ducimus maiores explicabo, ab officia
          at! Modi et porro illum, eligendi, vitae minima iure omnis ex culpa placeat officiis est odit sint. Blanditiis
          itaque minus nihil? Ut, ab maxime deleniti tempora optio, nesciunt hic velit voluptatem nulla sapiente ad
          quia.</p>
      </div>
    </section>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NerdChamps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <meta name="view-transition" content="same-origin" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>